// client/src/components/admin/Dashboard.tsx
import React from 'react'
import { Link } from 'react-router-dom'

import './Dashboard.css'

const Dashboard = () => (
  <div>
    <h1 className='text-center'>Dashboard</h1>
    <div className='text-center'>
      <Link to='/' className='btn bg-gray'>
        Blog Page
      </Link>
      <Link to='/create-post' className='btn bg-green'>
        Create Post
      </Link>
      <Link to='/create-tag' className='btn bg-green'>
        Create Tag
      </Link>
    </div>
  </div>
)

export default Dashboard

// vue-client/src/views/Dashboard/index.vue
<template>
  <div>
    <h1 class="text-center">Dashboard</h1>
    <div class="text-center">
      <router-link to="/" class="btn bg-gray">Blog Page</router-link>
      <router-link to="/create-post" class="btn bg-green">Create Post</router-link>
      <router-link to="/create-tag" class="btn bg-green">Create Tag</router-link>
    </div>
  </div>
</template>

<script>
export default {};
</script>

<style src="./style.css">
</style>
